# Generated by Django 3.1.2 on 2021-04-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0004_choosesizecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choosesizecolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choosesizecolor', to='Contents.choosesizecolor'),
        ),
    ]
