# Generated by Django 3.1.2 on 2021-04-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0007_auto_20210429_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addresspayment', to='Contents.address'),
        ),
    ]
