# Generated by Django 3.1.2 on 2021-05-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0008_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Contents.address'),
        ),
    ]
