# Generated by Django 3.1.2 on 2021-04-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0002_infomationusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='infomationUsers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contents.infomationusers'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contents.payment'),
        ),
    ]
