# Generated by Django 3.1.2 on 2021-04-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0006_auto_20210429_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomationusers',
            name='Addressinfo',
        ),
        migrations.AddField(
            model_name='infomationusers',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AddressUser', to='Contents.address'),
        ),
    ]
