# Generated by Django 3.1.2 on 2021-05-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0009_myorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment1', to='Contents.payment'),
        ),
    ]
